[tox]
envlist = py{311,312,313,314},check,doc
isolated_build = true

[testenv]
passenv = HOME
deps =
    py311: astropy==7.0.*
    py312: astropy==7.1.*
    py313: astropy==7.2.*
extras = tests,all
commands =
    python --version
    pip freeze -l
    pytest --cov mpdaf --cov-report term {posargs}

[testenv:check]
skip_install = true
deps =
    numpy
    docutils
    # check-manifest
    flake8
    collective.checkdocs
    pygments
    rstcheck
    # restructuredtext_lint
commands =
    python setup.py checkdocs
    python setup.py check --strict --metadata
    # check-manifest {toxinidir}
    rstcheck --report-level warning --ignore-messages "pull" README.rst CHANGELOG
    # rst-lint README.rst CHANGELOG

[testenv:docs]
changedir = doc
deps = pickleshare
extras = docs
whitelist_externals = sphinx-build
commands =
    sphinx-build {posargs:-W} . build/html
