name: Run unit tests

on:
  pull_request:
  push:
    branches:
    - master
    tags:
  workflow_dispatch:
  schedule:
    # Run every Sunday at 03:53 UTC
    - cron: 13 3 * * 0

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    name: ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: '3.11'
          - python-version: '3.12'
          - python-version: '3.13'
            nox_args: '--run-slow'
          - python-version: '3.14'
            nox_args: '--remote-data=any'

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install packages
      run: |
        sudo apt update
        sudo apt-get install libcfitsio-dev source-extractor
    - name: Install Nox
      run: python -m pip install nox coverage
    - name: Run tests
      run: nox -s coverage -- ${{ matrix.nox_args }}
    - name: Convert coverage
      run: python -m coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v6
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
